"""
Commands that turn the in-memory config into a human-readable file:

    view()  -> CLI `view`   writes .samengine/links.md  (Markdown, with **bold** etc.)
    viewx() -> CLI `viewx`  writes .samengine/links.txt (plain text)

Both functions build up one big string section by section (links, plain
text entries, imported package licenses, embedded license files, ...) and
then write it to disk in one go. They intentionally stay very similar to
each other - Markdown just adds `**bold**` / `*italic*` / `[]()` link
syntax around the same underlying data.
"""

from pathlib import Path

from ..config import AppConfig


# ---------- MARKDOWN FORMAT ----------

def view(config: AppConfig) -> None:
    """CLI `view`: render everything to Markdown at .samengine/links.md."""

    file = Path(".samengine/links.md")

    output = f"# Links for {config.projectname}\n\n"

    # Optional hand-written intro text (created empty by `init`).
    infoFile = Path(".samengine/links.info.md")

    if infoFile.exists():
        output += infoFile.read_text(encoding="utf8") + "\n\n"
    else:
        print("Info file doesnt exist!")

    output += f"Used for {config.projectname}:\n\n"

    # --- full Link entries ---
    for l in config.links:
        output += "- "

        if l.name:
            output += f"**{l.name}** "

        output += f"([{l.link}]({l.link})) "
        output += f"- {l.description} - "

        if l.author:
            output += f"by **{l.author}** "

        if l.license:
            output += f"licensed unter *{l.license}* "

        if l.licenselink:
            output += f"([{l.licenselink}]({l.licenselink})) "

        if l.changenotice:
            output += "- *(changes were made)*"

        if l.date:
            output += f" - *(saved at date: {l.date})*"

        output += "\n"

    # --- plain text entries (links2) ---
    for l in config.links2:
        output += f"- {l}\n"

    # --- simple text+date entries (links4) ---
    if config.links4 is not None:
        for l in config.links4:
            output += f"- {l.link} saved at date: **{l.date}**\n"

    # --- imported npm package-lock.json licenses ---
    if config.linkspkglock is not None:
        for item in config.linkspkglock:
            output += (
                f"- used **{item.name}** version {item.version} "
                f"licensed under **{item.license}** "
                f"- *[Link]({item.link})*\n"
            )

    # --- imported Cargo.lock licenses ---
    if config.linkscargolock is not None:
        for item in config.linkscargolock:
            output += (
                f"- used **{item.name}** version {item.version} "
                f"licensed under **{item.license}** "
                f"- *[Link]({item.link})*\n"
            )

    # --- legacy: raw license file paths (links3), embedded as code blocks ---
    for licenseFile in config.links3:
        path = Path(licenseFile)

        if path.exists():
            content = path.read_text(encoding="utf8")

            output += f"""
---

**license content from file: {licenseFile}**

```
{content}
```

"""
        else:
            print(f"Warning: License file '{licenseFile}' does not exist.")

    # --- license files with a date (links5), embedded as code blocks ---
    if config.links5 is not None:
        for item in config.links5:
            path = Path(item.link)

            if path.exists():
                content = path.read_text(encoding="utf8")

                output += f"""
---

**license content from file: {item.link}** at date: *{item.date}*

```
{content}
```

"""
            else:
                print(f"Warning: License file '{item.link}' does not exist.")

    output += """
---

*File generated by linksaver from s2* - [More Infos](https://shadowdara.wordpress.com/2026/06/30/minisite-a-site-in-only-one-html-file/)
"""

    file.write_text(output, encoding="utf8")

    print(
        """
Created File - Use parseMarkdown from samengine to make it into a nice html file.

npm i samengine
npx samengine markdown .samengine/links.md
"""
    )


# ---------- TXT FORMAT ----------

def viewx(config: AppConfig) -> None:
    """CLI `viewx`: render everything to plain text at .samengine/links.txt."""

    file = Path(".samengine/links.txt")

    output = f"Links for {config.projectname}\n\n"

    infoFile = Path(".samengine/links.info.txt")

    if infoFile.exists():
        output += infoFile.read_text(encoding="utf8") + "\n\n"
    else:
        print("Info file doesnt exist!")

    output += f"Used for {config.projectname}:\n\n"

    # --- full Link entries (no Markdown syntax here) ---
    for l in config.links:
        output += "- "

        if l.name:
            output += l.name

        output += f" ({l.link}) "
        output += f"- {l.description} - "

        if l.author:
            output += f"by {l.author} "

        if l.license:
            output += f"licensed unter {l.license} "

        if l.licenselink:
            output += f"({l.licenselink}) "

        if l.changenotice:
            output += "- (changes were made)"

        if l.date:
            output += f" - (saved at date: {l.date})"

        output += "\n"

    # --- plain text entries ---
    for l in config.links2:
        output += f"- {l}\n"

    # --- simple text+date entries ---
    if config.links4 is not None:
        for l in config.links4:
            output += f"- {l.link} saved at date: {l.date}\n"

    # --- legacy raw license file paths ---
    for licenseFile in config.links3:
        path = Path(licenseFile)

        if path.exists():
            content = path.read_text(encoding="utf8")

            output += f"""
license content from file: {licenseFile}

{content}

"""
        else:
            print(f"Warning: License file '{licenseFile}' does not exist.")

    # --- license files with a date ---
    if config.links5 is not None:
        for item in config.links5:
            path = Path(item.link)

            if path.exists():
                content = path.read_text(encoding="utf8")

                output += f"""
license content from file: {item.link} at date: {item.date}

{content}

"""
            else:
                print(f"Warning: License file '{item.link}' does not exist.")

    output += """
---

File generated by linksaver from s2 - https://shadowdara.wordpress.com/2026/06/30/minisite-a-site-in-only-one-html-file/
"""

    file.write_text(output, encoding="utf8")
